#! /usr/bin/env python


import ply.lex as lex

import os
import sys
from collections import defaultdict
import sys

reserved = {
	'===' : 'Triple_Equals',
	'BEGIN' : 'BEGIN',
	'import' : 'IMPORT',
	'END' : 'END',
	'__ENCODING__' : '__ENCODING__',
	'__END__' : '__END__',
	'__FILE__' : '__FILE__',
	'__LINE__' : '__LINE__',
	'alias' : 'ALIAS',
	'and' : 'AND',
	'begin' : 'BEGIN',
	'break' : 'BREAK',
	'case' : 'CASE',
	'class' : 'CLASS',
	'def' : 'DEF',
	
	'do' : 'DO',
	'else' : 'ELSE',
	'elsif' : 'ELSIF',
	'end' : 'END',
	'ensure' : 'ENSURE',
	'false' : 'FALSE',
	'for' : 'FOR',
	'if' : 'IF',
	'in' : 'IN',
	'module' : 'MODULE',
	'next' : 'NEXT',
	'nil' : 'NIL',
	'not' : 'NOT',
	'or' : 'OR',
	'redo' : 'REDO',
	'rescue' : 'RESCUE',
	'retry' : 'RETRY',
	'return' : 'RETURN',
	'self' : 'SELF',
	'super' : 'SUPER',
	'then' : 'THEN',
	'true' : 'TRUE',
	'undef' : 'UNDEF',
	'unless' : 'UNLESS',
	'until' : 'UNTIL',
	'when' : 'WHEN',
	'while' : 'WHILE',
	'yield' : 'YIELD',
	'DEBUG' : 'DEBUG',
	'DEBUG=' : 'DEBUG',
	'[]' : 'Sq_Brack1',
	'[]=' : 'Sq_Brack2',
	'_id2ref' : '_ID2REF',
	'abort' : 'ABORT',
	'abort_on_exception' : 'ABORT_ON_EXCEPTION',
	'abort_on_exception=' : 'ABORT_ON_EXCEPTION',
	'absolute_path' : 'ABSOLUTE_PATH',
	'acos' : 'ACOS',
	'acosh' : 'ACOSH',
	'add_stress_to_class' : 'ADD_STRESS_TO_CLASS',
	'aliases' : 'ALIASES',
	'all_symbols' : 'ALL_SYMBOLS',
	'argv0' : 'ARGV0',
	'asciicompat_encoding' : 'ASCIICOMPAT_ENCODING',
	'asin' : 'ASIN',
	'asinh' : 'ASINH',
	#'assoc' : 'ASSOC',
	'at' : 'AT',
	'atan' : 'ATAN',
	'atan2' : 'ATAN2',
	'atanh' : 'ATANH',
	'atime' : 'ATIME',
	'basename' : 'BASENAME',
	'binread' : 'BINREAD',
	'binwrite' : 'BINWRITE',
	'birthtime' : 'BIRTHTIME',
	'blockdev?' : 'BLOCKDEV',
	'cbrt' : 'CBRT',
	'change_privilege' : 'CHANGE_PRIVILEGE',
	'chardev?' : 'CHARDEV',
	'chdir' : 'CHDIR',
	'chmod' : 'CHMOD',
	'chown' : 'CHOWN',
	'chroot' : 'CHROOT',
	'clear' : 'CLEAR',
	'clock_getres' : 'CLOCK_GETRES',
	'clock_gettime' : 'CLOCK_GETTIME',
	'compatible?' : 'COMPATIBLE',
	'compile' : 'COMPILE',
	'compile_file' : 'COMPILE_FILE',
	'compile_option' : 'COMPILE_OPTION',
	'compile_option=' : 'COMPILE_OPTION',
	'constants' : 'CONSTANTS',
	'copy_stream' : 'COPY_STREAM',
	'cos' : 'COS',
	'cosh' : 'COSH',
	'count' : 'COUNT',
	'count_objects' : 'COUNT_OBJECTS',
	'ctime' : 'CTIME',
	'current' : 'CURRENT',
	'daemon' : 'DAEMON',
	'default_external' : 'DEFAULT_EXTERNAL',
	'default_external=' : 'DEFAULT_EXTERNAL',
	'default_internal' : 'DEFAULT_INTERNAL',
	'default_internal=' : 'DEFAULT_INTERNAL',
	'define_finalizer' : 'DEFINE_FINALIZER',
	'delete' : 'DELETE',
	'delete_if' : 'DELETE_IF',
	'detach' : 'DETACH',
	'directory?' : 'DIRECTORY',
	'dirname' : 'DIRNAME',
	'disable' : 'DISABLE',
	'disasm' : 'DISASM',
	'disassemble' : 'DISASSEMBLE',
	'dump' : 'DUMP',
	'each' : 'EACH',
	'each_key' : 'EACH_KEY',
	'each_object' : 'EACH_OBJECT',
	'each_pair' : 'EACH_PAIR',
	'each_value' : 'EACH_VALUE',
	'egid' : 'EGID',
	'egid=' : 'EGID',
	'eid' : 'EID',
	'empty?' : 'EMPTY',
	'enable' : 'ENABLE',
	'enabled?' : 'ENABLED',
	'entries' : 'ENTRIES',
	'erf' : 'ERF',
	'erfc' : 'ERFC',
	'escape' : 'ESCAPE',
	'euid' : 'EUID',
	'euid=' : 'EUID',
	'exception' : 'EXCEPTION',
	'exclusive' : 'EXCLUSIVE',
	'exec' : 'EXEC',
	'executable?' : 'EXECUTABLE',
	'executable_real?' : 'EXECUTABLE_REAL',
	'exist?' : 'EXIST',
	'exists?' : 'EXISTS',
	'exit' : 'EXIT',
	'exit!' : 'EXIT',
	'exp' : 'EXP',
	'expand_path' : 'EXPAND_PATH',
	'extname' : 'EXTNAME',
	'fetch' : 'FETCH',
	'file?' : 'FILE',
	'find' : 'FIND',
	'fnmatch' : 'FNMATCH',
	'fnmatch?' : 'FNMATCH',
	'for_fd' : 'FOR_FD',
	'foreach' : 'FOREACH',
	'fork' : 'FORK',
	'frexp' : 'FREXP',
	'from_name' : 'FROM_NAME',
	'ftype' : 'FTYPE',
	'gamma' : 'GAMMA',
	'garbage_collect' : 'GARBAGE_COLLECT',
	'getegid' : 'GETEGID',
	'geteuid' : 'GETEUID',
	'getgid' : 'GETGID',
	'getpgid' : 'GETPGID',
	'getpgrp' : 'GETPGRP',
	'getpriority' : 'GETPRIORITY',
	'getrlimit' : 'GETRLIMIT',
	'getsid' : 'GETSID',
	'getuid' : 'GETUID',
	'getwd' : 'GETWD',
	'gid' : 'GID',
	'gid=' : 'GID',
	'glob' : 'GLOB',
	'gm' : 'GM',
	'grant_privilege' : 'GRANT_PRIVILEGE',
	'groups' : 'GROUPS',
	'groups=' : 'GROUPS',
	'grpowned?' : 'GRPOWNED',
	'handle_interrupt' : 'HANDLE_INTERRUPT',
	'has_key?' : 'HAS_KEY',
	'has_value?' : 'HAS_VALUE',
	'home' : 'HOME',
	'hypot' : 'HYPOT',
	'identical?' : 'IDENTICAL',
	'include?' : 'INCLUDE',
	'index' : 'INDEX',
	'initgroups' : 'INITGROUPS',
	'inspect' : 'INSPECT',
	'invert' : 'INVERT',
	'issetugid' : 'ISSETUGID',
	'join' : 'JOIN',
	'keep_if' : 'KEEP_IF',
	'key' : 'KEY',
	'key?' : 'KEY',
	'keys' : 'KEYS',
	'kill' : 'KILL',
	'last_match' : 'LAST_MATCH',
	'latest_gc_info' : 'LATEST_GC_INFO',
	'lchmod' : 'LCHMOD',
	'lchown' : 'LCHOWN',
	'ldexp' : 'LDEXP',
	'length' : 'LENGTH',
	'lgamma' : 'LGAMMA',
	'link' : 'LINK',
	'list' : 'LIST',
	'load' : 'LOAD',
	'load_from_binary' : 'LOAD_FROM_BINARY',
	'load_from_binary_extra_data' : 'LOAD_FROM_BINARY_EXTRA_DATA',
	'local' : 'LOCAL',
	'locale_charmap' : 'LOCALE_CHARMAP',
	'log' : 'LOG',
	'log10' : 'LOG10',
	'log2' : 'LOG2',
	'lstat' : 'LSTAT',
	'main' : 'MAIN',
	'malloc_allocated_size' : 'MALLOC_ALLOCATED_SIZE',
	'malloc_allocations' : 'MALLOC_ALLOCATIONS',
	'maxgroups' : 'MAXGROUPS',
	'maxgroups=' : 'MAXGROUPS',
	'member?' : 'MEMBER',
	'mkdir' : 'MKDIR',
	'mkfifo' : 'MKFIFO',
	'mktime' : 'MKTIME',
	'mtime' : 'MTIME',
	'name_list' : 'NAME_LIST',
	'nesting' : 'NESTING',
	'new' : 'NEW',
	'new_seed' : 'NEW_SEED',
	'now' : 'NOW',
	'of' : 'OF',
	'open' : 'OPEN',
	'owned?' : 'OWNED',
	'pass' : 'PASS',
	'path' : 'PATH',
	'pending_interrupt?' : 'PENDING_INTERRUPT',
	'pid' : 'PID',
	'pipe' : 'PIPE',
	'pipe?' : 'PIPE',
	'polar' : 'POLAR',
	'popen' : 'POPEN',
	'ppid' : 'PPID',
	'pwd' : 'PWD',
	'quote' : 'QUOTE',
	'rand' : 'RAND',
	'rassoc' : 'RASSOC',
	'raw_data' : 'RAW_DATA',
	'raw_seed' : 'RAW_SEED',
	're_exchange' : 'RE_EXCHANGE',
	're_exchangeable?' : 'RE_EXCHANGEABLE',
	'read' : 'READ',
	'readable?' : 'READABLE',
	'readable_real?' : 'READABLE_REAL',
	'readlines' : 'READLINES',
	'readlink' : 'READLINK',
	'realdirpath' : 'REALDIRPATH',
	'realpath' : 'REALPATH',
	'rect' : 'RECT',
	'rectangular' : 'RECTANGULAR',
	'rehash' : 'REHASH',
	'reject' : 'REJECT',
	'reject!' : 'REJECTS',
	'remove_stress_to_class' : 'REMOVE_STRESS_TO_CLASS',
	'rename' : 'RENAME',
	'replace' : 'REPLACE',
	'report' : 'REPORT',
	'restore' : 'RESTORE',
	'result' : 'RESULT',
	'rid' : 'RID',
	'rmdir' : 'RMDIR',
	'search_convpath' : 'SEARCH_CONVPATH',
	'select' : 'SELECT',
	'select!' : 'SELECT',
	'setegid' : 'SETEGID',
	'seteuid' : 'SETEUID',
	'setgid' : 'SETGID',
	'setgid?' : 'SETGID',
	'setpgid' : 'SETPGID',
	'setpgrp' : 'SETPGRP',
	'setpriority' : 'SETPRIORITY',
	'setproctitle' : 'SETPROCTITLE',
	'setregid' : 'SETREGID',
	'setresgid' : 'SETRESGID',
	'setresuid' : 'SETRESUID',
	'setreuid' : 'SETREUID',
	'setrgid' : 'SETRGID',
	'setrlimit' : 'SETRLIMIT',
	'setruid' : 'SETRUID',
	'setsid' : 'SETSID',
	'setuid' : 'SETUID',
	'setuid?' : 'SETUID',
	'shift' : 'SHIFT',
	'sid_available?' : 'SID_AVAILABLE',
	'signame' : 'SIGNAME',
	'sin' : 'SIN',
	'sinh' : 'SINH',
	'size' : 'SIZE',
	'size?' : 'SIZE',
	'socket?' : 'SOCKET',
	'spawn' : 'SPAWN',
	'split' : 'SPLIT',
	'sqrt' : 'SQRT',
	'srand' : 'SRAND',
	'start' : 'START',
	'stat' : 'STAT',
	'sticky?' : 'STICKY',
	'stop' : 'STOP',
	'store' : 'STORE',
	'stress' : 'STRESS',
	'stress=' : 'STRESS',
	'switch' : 'SWITCH',
	'symlink' : 'SYMLINK',
	'symlink?' : 'SYMLINK',
	'sysopen' : 'SYSOPEN',
	'tan' : 'TAN',
	'tanh' : 'TANH',
	'times' : 'TIMES',
	'to_a' : 'TO_A',
	'to_h' : 'TO_H',
	'to_hash' : 'TO_HASH',
	'to_s' : 'TO_S',
	'total_time' : 'TOTAL_TIME',
	'trace' : 'TRACE',
	'trap' : 'TRAP',
	'truncate' : 'TRUNCATE',
	'try_convert' : 'TRY_CONVERT',
	'uid' : 'UID',
	'uid=' : 'UID',
	'umask' : 'UMASK',
	'undefine_finalizer' : 'UNDEFINE_FINALIZER',
	'union' : 'UNION',
	'unlink' : 'UNLINK',
	'update' : 'UPDATE',
	'utc' : 'UTC',
	'utime' : 'UTIME',
	'value?' : 'VALUE',
	'values' : 'VALUES',
	'values_at' : 'VALUES_AT',
	'verify_internal_consistency' : 'VERIFY_INTERNAL_CONSISTENCY',
	'wait' : 'WAIT',
	'wait2' : 'WAIT2',
	'waitall' : 'WAITALL',
	'waitpid' : 'WAITPID',
	'waitpid2' : 'WAITPID2',
	'world_readable?' : 'WORLD_READABLE',
	'world_writable?' : 'WORLD_WRITABLE',
	'writable?' : 'WRITABLE',
	'writable_real?' : 'WRITABLE_REAL',
	'write' : 'WRITE',
	'yield' : 'YIELD',
	'zero?' : 'ZERO',
	'!' : 'Exclaimation',
	'[' : 'OPENSQUARE',
	']' : 'CLOSEDSQUARE',
	'!=' : 'Exclaim1',
	'!~' : 'Exclaim2',
	'%' : 'Percentage',
	'&' : 'And',
	'*' : 'Multiply',
	'**' : 'Exponent',
	'+' : 'Add',
	'+@' : 'Add1',
	'-' : 'hyphun',
	'-@' : 'hyphun1',
	'/' : 'backslash',
	'<' : 'less_than',
	'<<' : 'stdout',
	'<=' : 'lessthan_equals',
	'<=>' : 'less_equal_more',
	'==' : 'double_equals',
	'=~' : 'equal1',
	'>' : 'greater_than',
	'>=' : 'greater_than_equals',
	'>>' : 'stdin',
	'+=' : 'PLUS_EQUALS',
	'-=' : 'MINUS_EQUALS',
	'*=' : 'MULTIPLY_EQUALS',
	'/=' : 'DIVIDE_EQUALS',
	'Array' : 'ARRAY',
	'Complex' : 'COMPLEX',
	'Float' : 'FLOAT',
	'Hash' : 'HASH',
	'Integer' : 'INTEGER',
	'Rational' : 'RATIONAL',
	'String' : 'STRING',
	'^' : 'CARROT',
	'__callee__' : '__CALLEE',
	'__dir__' : '__DIR',
	'__id__' : '__ID',
	'__method__' : '__METHOD',
	'__send__' : '__SEND',
	'`' : 'Apostophe',
	'abort' : 'ABORT',
	'abort_on_exception' : 'ABORT_ON_EXCEPTION',
	'abort_on_exception=' : 'ABORT_ON_EXCEPTION',
	'abs' : 'ABS',
	'abs2' : 'ABS2',
	'absolute_path' : 'ABSOLUTE_PATH',
	'add' : 'ADD',
	'add_trace_func' : 'ADD_TRACE_FUNC',
	'advise' : 'ADVISE',
	'alias_method' : 'ALIAS_METHOD',
	'alive?' : 'ALIVE',
	'all?' : 'ALL',
	'allocate' : 'ALLOCATE',
	'ancestors' : 'ANCESTORS',
	'angle' : 'ANGLE',
	'any?' : 'ANY',
	'append_features' : 'APPEND_FEATURES',
	#'arg' : 'ARG',
	#'args' : 'ARGS',
	'arity' : 'ARITY',
	'ascii_compatible?' : 'ASCII_COMPATIBLE',
	'ascii_only?' : 'ASCII_ONLY',
	'asctime' : 'ASCTIME',
	#'assoc' : 'ASSOC',
	'at' : 'AT',
	'at_exit' : 'AT_EXIT',
	'atime' : 'ATIME',
	'attr' : 'ATTR',
	'attr_accessor' : 'ATTR_ACCESSOR',
	'attr_reader' : 'ATTR_READER',
	'attr_writer' : 'ATTR_WRITER',
	'autoclose=' : 'AUTOCLOSE',
	'autoclose?' : 'AUTOCLOSE',
	'autoload' : 'AUTOLOAD',
	'autoload?' : 'AUTOLOAD',
	'backtrace' : 'BACKTRACE',
	'backtrace_locations' : 'BACKTRACE_LOCATIONS',
	'base_label' : 'BASE_LABEL',
	'begin' : 'BEGIN',
	'between?' : 'BETWEEN',
	'bind' : 'BIND',
	'binding' : 'BINDING',
	'binmode' : 'BINMODE',
	'binmode?' : 'BINMODE',
	'birthtime' : 'BIRTHTIME',
	'bit_length' : 'BIT_LENGTH',
	'blksize' : 'BLKSIZE',
	'block_given?' : 'BLOCK_GIVEN',
	'blockdev?' : 'BLOCKDEV',
	'blocks' : 'BLOCKS',
	'broadcast' : 'BROADCAST',
	'bsearch' : 'BSEARCH',
	'bsearch_index' : 'BSEARCH_INDEX',
	'bytes' : 'BYTES',
	'bytesize' : 'BYTESIZE',
	'byteslice' : 'BYTESLICE',
	'call' : 'CALL',
	'callcc' : 'CALLCC',
	'caller' : 'CALLER',
	'caller_locations' : 'CALLER_LOCATIONS',
	'capitalize' : 'CAPITALIZE',
	'capitalize!' : 'CAPITALIZE',
	'captures' : 'CAPTURES',
	'casecmp' : 'CASECMP',
	'casefold?' : 'CASEFOLD',
	'catch' : 'CATCH',
	'cause' : 'CAUSE',
	'ceil' : 'CEIL',
	'center' : 'CENTER',
	'chardev?' : 'CHARDEV',
	'chars' : 'CHARS',
	'chmod' : 'CHMOD',
	'chomp' : 'CHOMP',
	'chomp!' : 'CHOMP',
	'chop' : 'CHOP',
	'chop!' : 'CHOP',
	'chown' : 'CHOWN',
	'chr' : 'CHR',
	'chunk' : 'CHUNK',
	'chunk_while' : 'CHUNK_WHILE',
	'class' : 'CLASS',
	'class_eval' : 'CLASS_EVAL',
	'class_exec' : 'CLASS_EXEC',
	'class_variable_defined?' : 'CLASS_VARIABLE_DEFINED',
	'class_variable_get' : 'CLASS_VARIABLE_GET',
	'class_variable_set' : 'CLASS_VARIABLE_SET',
	'class_variables' : 'CLASS_VARIABLES',
	'clear' : 'CLEAR',
	'clone' : 'CLONE',
	'close' : 'CLOSE',
	'close_on_exec=' : 'CLOSE_ON_EXEC',
	'close_on_exec?' : 'CLOSE_ON_EXEC',
	'close_read' : 'CLOSE_READ',
	'close_write' : 'CLOSE_WRITE',
	'closed?' : 'CLOSED',
	'codepoints' : 'CODEPOINTS',
	'coerce' : 'COERCE',
	'collect' : 'COLLECT',
	'collect!' : 'COLLECT',
	'collect_concat' : 'COLLECT_CONCAT',
	'combination' : 'COMBINATION',
	'compact' : 'COMPACT',
	'compact!' : 'COMPACT',
	'compare_by_identity' : 'COMPARE_BY_IDENTITY',
	'compare_by_identity?' : 'COMPARE_BY_IDENTITY',
	'concat' : 'CONCAT',
	'conj' : 'CONJ',
	'conjugate' : 'CONJUGATE',
	'const_defined?' : 'CONST_DEFINED',
	'const_get' : 'CONST_GET',
	'const_missing' : 'CONST_MISSING',
	'const_set' : 'CONST_SET',
	'constants' : 'CONSTANTS',
	'convert' : 'CONVERT',
	'convpath' : 'CONVPATH',
	'coredump?' : 'COREDUMP',
	'count' : 'COUNT',
	'cover?' : 'COVER',
	'crypt' : 'CRYPT',
	'ctime' : 'CTIME',
	'curry' : 'CURRY',
	'cycle' : 'CYCLE',
	'day' : 'DAY',
	'default' : 'DEFAULT',
	'default=' : 'DEFAULT',
	'default_proc' : 'DEFAULT_PROC',
	'default_proc=' : 'DEFAULT_PROC',
	'define_method' : 'DEFINE_METHOD',
	'define_singleton_method' : 'DEFINE_SINGLETON_METHOD',
	'defined_class' : 'DEFINED_CLASS',
	'delete' : 'DELETE',
	'delete!' : 'DELETE',
	'delete_at' : 'DELETE_AT',
	'delete_if' : 'DELETE_IF',
	'denominator' : 'DENOMINATOR',
	'deprecate_constant' : 'DEPRECATE_CONSTANT',
	'deq' : 'DEQ',
	'destination_encoding' : 'DESTINATION_ENCODING',
	'destination_encoding_name' : 'DESTINATION_ENCODING_NAME',
	'detect' : 'DETECT',
	'dev' : 'DEV',
	'dev_major' : 'DEV_MAJOR',
	'dev_minor' : 'DEV_MINOR',
	'dig' : 'DIG',
	'directory?' : 'DIRECTORY',
	'disable' : 'DISABLE',
	'disasm' : 'DISASM',
	'disassemble' : 'DISASSEMBLE',
	'display' : 'DISPLAY',
	'div' : 'DIV',
	'divmod' : 'DIVMOD',
	'downcase' : 'DOWNCASE',
	'downcase!' : 'DOWNCASE',
	'downto' : 'DOWNTO',
	'drop' : 'DROP',
	'drop_while' : 'DROP_WHILE',
	'dst?' : 'DST',
	'dummy?' : 'DUMMY',
	'dump' : 'DUMP',
	'dup' : 'DUP',
	'each' : 'EACH',
	'each_byte' : 'EACH_BYTE',
	'each_char' : 'EACH_CHAR',
	'each_codepoint' : 'EACH_CODEPOINT',
	'each_cons' : 'EACH_CONS',
	'each_entry' : 'EACH_ENTRY',
	'each_index' : 'EACH_INDEX',
	'each_key' : 'EACH_KEY',
	'each_line' : 'EACH_LINE',
	'each_pair' : 'EACH_PAIR',
	'each_slice' : 'EACH_SLICE',
	'each_value' : 'EACH_VALUE',
	'each_with_index' : 'EACH_WITH_INDEX',
	'each_with_object' : 'EACH_WITH_OBJECT',
	'empty?' : 'EMPTY',
	'enable' : 'ENABLE',
	'enabled?' : 'ENABLED',
	'enclose' : 'ENCLOSE',
	'enclosed?' : 'ENCLOSED',
	'encode' : 'ENCODE',
	'encode!' : 'ENCODE',
	'encoding' : 'ENCODING',
	'end' : 'END',
	'end_with?' : 'END_WITH',
	'enq' : 'ENQ',
	'entries' : 'ENTRIES',
	'enum_for' : 'ENUM_FOR',
	'eof' : 'EOF',
	'eof?' : 'EOF',
	'eql?' : 'EQL',
	'equal?' : 'EQUAL',
	'errno' : 'ERRNO',
	'error_bytes' : 'ERROR_BYTES',
	'error_char' : 'ERROR_CHAR',
	'eval' : 'EVAL',
	'even?' : 'EVEN',
	'event' : 'EVENT',
	'exception' : 'EXCEPTION',
	'exclude_end?' : 'EXCLUDE_END',
	'exec' : 'EXEC',
	'executable?' : 'EXECUTABLE',
	'executable_real?' : 'EXECUTABLE_REAL',
	'exist?' : 'EXIST',
	'exists?' : 'EXISTS',
	'exit' : 'EXIT',
	'exit!' : 'EXIT',
	'exit_value' : 'EXIT_VALUE',
	'exited?' : 'EXITED',
	'exitstatus' : 'EXITSTATUS',
	'extend' : 'EXTEND',
	'extend_object' : 'EXTEND_OBJECT',
	'extended' : 'EXTENDED',
	'external_encoding' : 'EXTERNAL_ENCODING',
	'fail' : 'FAIL',
	'fcntl' : 'FCNTL',
	'fdatasync' : 'FDATASYNC',
	'fdiv' : 'FDIV',
	'feed' : 'FEED',
	'fetch' : 'FETCH',
	'fetch_values' : 'FETCH_VALUES',
	'file?' : 'FILE',
	'fileno' : 'FILENO',
	'fill' : 'FILL',
	'finalize' : 'FINALIZE',
	'find' : 'FIND',
	'find_all' : 'FIND_ALL',
	'find_index' : 'FIND_INDEX',
	'finish' : 'FINISH',
	'finite?' : 'FINITE',
	'first' : 'FIRST',
	'first_lineno' : 'FIRST_LINENO',
	'fixed_encoding?' : 'FIXED_ENCODING',
	'flat_map' : 'FLAT_MAP',
	'flatten' : 'FLATTEN',
	'flatten!' : 'FLATTEN',
	'flock' : 'FLOCK',
	'floor' : 'FLOOR',
	'flush' : 'FLUSH',
	'force_encoding' : 'FORCE_ENCODING',
	'fork' : 'FORK',
	'format' : 'FORMAT',
	'freeze' : 'FREEZE',
	'friday?' : 'FRIDAY',
	'frozen?' : 'FROZEN',
	'fsync' : 'FSYNC',
	'ftype' : 'FTYPE',
	'garbage_collect' : 'GARBAGE_COLLECT',
	'gcd' : 'GCD',
	'gcdlcm' : 'GCDLCM',
	'getbyte' : 'GETBYTE',
	'getc' : 'GETC',
	'getgm' : 'GETGM',
	'getlocal' : 'GETLOCAL',
	'gets' : 'GETS',
	'getutc' : 'GETUTC',
	'gid' : 'GID',
	'global_variables' : 'GLOBAL_VARIABLES',
	'gmt?' : 'GMT',
	'gmt_offset' : 'GMT_OFFSET',
	'gmtime' : 'GMTIME',
	'gmtoff' : 'GMTOFF',
	'grep' : 'GREP',
	'grep_v' : 'GREP_V',
	'group' : 'GROUP',
	'group_by' : 'GROUP_BY',
	'grpowned?' : 'GRPOWNED',
	'gsub' : 'GSUB',
	'gsub!' : 'GSUB',
	'has_key?' : 'HAS_KEY',
	'has_value?' : 'HAS_VALUE',
	'hash' : 'HASH',
	'hex' : 'HEX',
	'hour' : 'HOUR',
	'id2name' : 'ID2NAME',
	'identical?' : 'IDENTICAL',
	'imag' : 'IMAG',
	'imaginary' : 'IMAGINARY',
	'include' : 'INCLUDE',
	'include?' : 'INCLUDE',
	'included' : 'INCLUDED',
	'included_modules' : 'INCLUDED_MODULES',
	'incomplete_input?' : 'INCOMPLETE_INPUT',
	'index' : 'INDEX',
	'infinite?' : 'INFINITE',
	'inherited' : 'INHERITED',
	'initialize_copy' : 'INITIALIZE_COPY',
	'inject' : 'INJECT',
	'ino' : 'INO',
	'insert' : 'INSERT',
	'insert_output' : 'INSERT_OUTPUT',
	'inspect' : 'INSPECT',
	'instance_eval' : 'INSTANCE_EVAL',
	'instance_exec' : 'INSTANCE_EXEC',
	'instance_method' : 'INSTANCE_METHOD',
	'instance_methods' : 'INSTANCE_METHODS',
	'instance_of?' : 'INSTANCE_OF',
	'instance_variable_defined?' : 'INSTANCE_VARIABLE_DEFINED',
	'instance_variable_get' : 'INSTANCE_VARIABLE_GET',
	'instance_variable_set' : 'INSTANCE_VARIABLE_SET',
	'instance_variables' : 'INSTANCE_VARIABLES',
	'integer?' : 'INTEGER',
	'intern' : 'INTERN',
	'internal_encoding' : 'INTERNAL_ENCODING',
	'invert' : 'INVERT',
	'ioctl' : 'IOCTL',
	'is_a?' : 'IS_A',
	'isatty' : 'ISATTY',
	'isdst' : 'ISDST',
	'iterator?' : 'ITERATOR',
	'itself' : 'ITSELF',
	'join' : 'JOIN',
	'keep_if' : 'KEEP_IF',
	'key' : 'KEY',
	'key?' : 'KEY',
	'keys' : 'KEYS',
	'kill' : 'KILL',
	'kind_of?' : 'KIND_OF',
	'label' : 'LABEL',
	'lambda' : 'LAMBDA',
	'lambda?' : 'LAMBDA',
	'last' : 'LAST',
	'last_error' : 'LAST_ERROR',
	'lazy' : 'LAZY',
	'lcm' : 'LCM',
	'length' : 'LENGTH',
	'line_trace_all' : 'LINE_TRACE_ALL',
	'line_trace_specify' : 'LINE_TRACE_SPECIFY',
	'lineno' : 'LINENO',
	'lineno=' : 'LINENO',
	'lines' : 'LINES',
	'list' : 'LIST',
	'ljust' : 'LJUST',
	'load' : 'LOAD',
	'local_variable_defined?' : 'LOCAL_VARIABLE_DEFINED',
	'local_variable_get' : 'LOCAL_VARIABLE_GET',
	'local_variable_set' : 'LOCAL_VARIABLE_SET',
	'local_variables' : 'LOCAL_VARIABLES',
	'localtime' : 'LOCALTIME',
	'lock' : 'LOCK',
	'locked?' : 'LOCKED',
	'loop' : 'LOOP',
	'lstat' : 'LSTAT',
	'lstrip' : 'LSTRIP',
	'lstrip!' : 'LSTRIP',
	'magnitude' : 'MAGNITUDE',
	'map' : 'MAP',
	'map!' : 'MAP',
	'match' : 'MATCH',
	'max' : 'MAX',
	'max=' : 'MAX',
	'max_by' : 'MAX_BY',
	'mday' : 'MDAY',
	'member?' : 'MEMBER',
	'members' : 'MEMBERS',
	'merge' : 'MERGE',
	'merge!' : 'MERGE',
	'message' : 'MESSAGE',
	'method' : 'METHOD',
	'method_added' : 'METHOD_ADDED',
	'method_defined?' : 'METHOD_DEFINED',
	'method_id' : 'METHOD_ID',
	'method_missing' : 'METHOD_MISSING',
	'method_removed' : 'METHOD_REMOVED',
	'method_undefined' : 'METHOD_UNDEFINED',
	'methods' : 'METHODS',
	'min' : 'MIN',
	'min_by' : 'MIN_BY',
	'minmax' : 'MINMAX',
	'minmax_by' : 'MINMAX_BY',
	'mode' : 'MODE',
	'module_eval' : 'MODULE_EVAL',
	'module_exec' : 'MODULE_EXEC',
	'module_function' : 'MODULE_FUNCTION',
	'modulo' : 'MODULO',
	'mon' : 'MON',
	'monday?' : 'MONDAY',
	'month' : 'MONTH',
	'mtime' : 'MTIME',
	'name' : 'NAME',
	'name=' : 'NAME',
	'named_captures' : 'NAMED_CAPTURES',
	'names' : 'NAMES',
	'nan?' : 'NAN',
	'negative?' : 'NEGATIVE',
	'new' : 'NEW',
	'next' : 'NEXT',
	'next!' : 'NEXT',
	'next_float' : 'NEXT_FLOAT',
	'next_values' : 'NEXT_VALUES',
	'nil?' : 'NIL',
	'nlink' : 'NLINK',
	'none?' : 'NONE',
	'nonzero?' : 'NONZERO',
	'nsec' : 'NSEC',
	'num_waiting' : 'NUM_WAITING',
	'numerator' : 'NUMERATOR',
	'object_id' : 'OBJECT_ID',
	'oct' : 'OCT',
	'odd?' : 'ODD',
	'offset' : 'OFFSET',
	'one?' : 'ONE',
	'open' : 'OPEN',
	'options' : 'OPTIONS',
	'ord' : 'ORD',
	'original_name' : 'ORIGINAL_NAME',
	'owned?' : 'OWNED',
	'owner' : 'OWNER',
	'p' : 'P',
	'pack' : 'PACK',
	'parameters' : 'PARAMETERS',
	'partition' : 'PARTITION',
	'path' : 'PATH',
	'peek' : 'PEEK',
	'peek_values' : 'PEEK_VALUES',
	'pending_interrupt?' : 'PENDING_INTERRUPT',
	'permutation' : 'PERMUTATION',
	'phase' : 'PHASE',
	'pid' : 'PID',
	'pipe?' : 'PIPE',
	'polar' : 'POLAR',
	'pop' : 'POP',
	'pos' : 'POS',
	'pos=' : 'POS',
	'positive?' : 'POSITIVE',
	'post_match' : 'POST_MATCH',
	'pre_match' : 'PRE_MATCH',
	'pred' : 'PRED',
	'prepend' : 'PREPEND',
	'prepend_features' : 'PREPEND_FEATURES',
	'prepended' : 'PREPENDED',
	'prev_float' : 'PREV_FLOAT',
	'primitive_convert' : 'PRIMITIVE_CONVERT',
	'primitive_errinfo' : 'PRIMITIVE_ERRINFO',
	'print' : 'PRINT',
	'printf' : 'PRINTF',
	'priority' : 'PRIORITY',
	'priority=' : 'PRIORITY',
	'private' : 'PRIVATE',
	'private_class_method' : 'PRIVATE_CLASS_METHOD',
	'private_constant' : 'PRIVATE_CONSTANT',
	'private_instance_methods' : 'PRIVATE_INSTANCE_METHODS',
	'private_method_defined?' : 'PRIVATE_METHOD_DEFINED',
	'private_methods' : 'PRIVATE_METHODS',
	'proc' : 'PROC',
	'product' : 'PRODUCT',
	'protected' : 'PROTECTED',
	'protected_instance_methods' : 'PROTECTED_INSTANCE_METHODS',
	'protected_method_defined?' : 'PROTECTED_METHOD_DEFINED',
	'protected_methods' : 'PROTECTED_METHODS',
	'public' : 'PUBLIC',
	'public_class_method' : 'PUBLIC_CLASS_METHOD',
	'public_constant' : 'PUBLIC_CONSTANT',
	'public_instance_method' : 'PUBLIC_INSTANCE_METHOD',
	'public_instance_methods' : 'PUBLIC_INSTANCE_METHODS',
	'public_method' : 'PUBLIC_METHOD',
	'public_method_defined?' : 'PUBLIC_METHOD_DEFINED',
	'public_methods' : 'PUBLIC_METHODS',
	'public_send' : 'PUBLIC_SEND',
	'push' : 'PUSH',
	'putback' : 'PUTBACK',
	'putc' : 'PUTC',
	'puts' : 'PUTS',
	'quo' : 'QUO',
	'raise' : 'RAISE',
	'raised_exception' : 'RAISED_EXCEPTION',
	'rand' : 'RAND',
	'random_number' : 'RANDOM_NUMBER',
	'rassoc' : 'RASSOC',
	'rationalize' : 'RATIONALIZE',
	'rdev' : 'RDEV',
	'rdev_major' : 'RDEV_MAJOR',
	'rdev_minor' : 'RDEV_MINOR',
	'read' : 'READ',
	'read_nonblock' : 'READ_NONBLOCK',
	'readable?' : 'READABLE',
	'readable_real?' : 'READABLE_REAL',
	'readagain_bytes' : 'READAGAIN_BYTES',
	'readbyte' : 'READBYTE',
	'readchar' : 'READCHAR',
	'readline' : 'READLINE',
	'readlines' : 'READLINES',
	'readpartial' : 'READPARTIAL',
	'real' : 'REAL',
	'real?' : 'REAL',
	'reason' : 'REASON',
	'receiver' : 'RECEIVER',
	'rect' : 'RECT',
	'rectangular' : 'RECTANGULAR',
	'reduce' : 'REDUCE',
	'refine' : 'REFINE',
	'regexp' : 'REGEXP',
	'rehash' : 'REHASH',
	'reject' : 'REJECT',
	'reject!' : 'REJECT',
	'remainder' : 'REMAINDER',
	'remove_class_variable' : 'REMOVE_CLASS_VARIABLE',
	'remove_const' : 'REMOVE_CONST',
	'remove_instance_variable' : 'REMOVE_INSTANCE_VARIABLE',
	'remove_method' : 'REMOVE_METHOD',
	'reopen' : 'REOPEN',
	'repeated_combination' : 'REPEATED_COMBINATION',
	'repeated_permutation' : 'REPEATED_PERMUTATION',
	'replace' : 'REPLACE',
	'replacement' : 'REPLACEMENT',
	'replacement=' : 'REPLACEMENT',
	'replicate' : 'REPLICATE',
	'require' : 'REQUIRE',
	'require_relative' : 'REQUIRE_RELATIVE',
	'respond_to?' : 'RESPOND_TO',
	'respond_to_missing?' : 'RESPOND_TO_MISSING',
	'result' : 'RESULT',
	'resume' : 'RESUME',
	'return_value' : 'RETURN_VALUE',
	'reverse' : 'REVERSE',
	'reverse!' : 'REVERSE',
	'reverse_each' : 'REVERSE_EACH',
	'rewind' : 'REWIND',
	'rindex' : 'RINDEX',
	'rjust' : 'RJUST',
	'rotate' : 'ROTATE',
	'rotate!' : 'ROTATE',
	'round' : 'ROUND',
	'rpartition' : 'RPARTITION',
	'rstrip' : 'RSTRIP',
	'rstrip!' : 'RSTRIP',
	'run' : 'RUN',
	'safe_level' : 'SAFE_LEVEL',
	'sample' : 'SAMPLE',
	'saturday?' : 'SATURDAY',
	'scan' : 'SCAN',
	'scrub' : 'SCRUB',
	'scrub!' : 'SCRUB',
	'sec' : 'SEC',
	'seed' : 'SEED',
	'seek' : 'SEEK',
	'select' : 'SELECT',
	'select!' : 'SELECT',
	'self' : 'SELF',
	'send' : 'SEND',
	'set_backtrace' : 'SET_BACKTRACE',
	'set_encoding' : 'SET_ENCODING',
	'set_trace_func' : 'SET_TRACE_FUNC',
	'setbyte' : 'SETBYTE',
	'setgid?' : 'SETGID',
	'setuid?' : 'SETUID',
	'shift' : 'SHIFT',
	'shuffle' : 'SHUFFLE',
	'shuffle!' : 'SHUFFLE',
	'signal' : 'SIGNAL',
	'signaled?' : 'SIGNALED',
	'signo' : 'SIGNO',
	'singleton_class' : 'SINGLETON_CLASS',
	'singleton_class?' : 'SINGLETON_CLASS',
	'singleton_method' : 'SINGLETON_METHOD',
	'singleton_method_added' : 'SINGLETON_METHOD_ADDED',
	'singleton_method_removed' : 'SINGLETON_METHOD_REMOVED',
	'singleton_method_undefined' : 'SINGLETON_METHOD_UNDEFINED',
	'singleton_methods' : 'SINGLETON_METHODS',
	'size' : 'SIZE',
	'size?' : 'SIZE',
	'sleep' : 'SLEEP',
	'slice' : 'SLICE',
	'slice!' : 'SLICE',
	'slice_after' : 'SLICE_AFTER',
	'slice_before' : 'SLICE_BEFORE',
	'slice_when' : 'SLICE_WHEN',
	'socket?' : 'SOCKET',
	'sort' : 'SORT',
	'sort!' : 'SORT',
	'sort_by' : 'SORT_BY',
	'sort_by!' : 'SORT_BY',
	'source' : 'SOURCE',
	'source_encoding' : 'SOURCE_ENCODING',
	'source_encoding_name' : 'SOURCE_ENCODING_NAME',
	'source_location' : 'SOURCE_LOCATION',
	'spawn' : 'SPAWN',
	'split' : 'SPLIT',
	'sprintf' : 'SPRINTF',
	'squeeze' : 'SQUEEZE',
	'squeeze!' : 'SQUEEZE',
	'srand' : 'SRAND',
	'start_with?' : 'START_WITH',
	'stat' : 'STAT',
	'status' : 'STATUS',
	'step' : 'STEP',
	'sticky?' : 'STICKY',
	'stop?' : 'STOP',
	'stopped?' : 'STOPPED',
	'stopsig' : 'STOPSIG',
	'store' : 'STORE',
	'strftime' : 'STRFTIME',
	'string' : 'STRING',
	'strip' : 'STRIP',
	'strip!' : 'STRIP',
	'sub' : 'SUB',
	'sub!' : 'SUB',
	'subsec' : 'SUBSEC',
	'succ' : 'SUCC',
	'succ!' : 'SUCC',
	'success?' : 'SUCCESS',
	'sum' : 'SUM',
	'sunday?' : 'SUNDAY',
	'super_method' : 'SUPER_METHOD',
	'superclass' : 'SUPERCLASS',
	'swapcase' : 'SWAPCASE',
	'swapcase!' : 'SWAPCASE',
	'symlink?' : 'SYMLINK',
	'sync' : 'SYNC',
	'sync=' : 'SYNC',
	'synchronize' : 'SYNCHRONIZE',
	'syscall' : 'SYSCALL',
	'sysread' : 'SYSREAD',
	'sysseek' : 'SYSSEEK',
	'system' : 'SYSTEM',
	'syswrite' : 'SYSWRITE',
	'tag' : 'TAG',
	'taint' : 'TAINT',
	'tainted?' : 'TAINTED',
	'take' : 'TAKE',
	'take_while' : 'TAKE_WHILE',
	'tap' : 'TAP',
	'tell' : 'TELL',
	'terminate' : 'TERMINATE',
	'termsig' : 'TERMSIG',
	'test' : 'TEST',
	'thread_variable?' : 'THREAD_VARIABLE',
	'thread_variable_get' : 'THREAD_VARIABLE_GET',
	'thread_variable_set' : 'THREAD_VARIABLE_SET',
	'thread_variables' : 'THREAD_VARIABLES',
	'throw' : 'THROW',
	'thursday?' : 'THURSDAY',
	'times' : 'TIMES',
	'to_a' : 'TO_A',
	'to_ary' : 'TO_ARY',
	'to_binary' : 'TO_BINARY',
	'to_c' : 'TO_C',
	'to_enum' : 'TO_ENUM',
	'to_f' : 'TO_F',
	'to_h' : 'TO_H',
	'to_hash' : 'TO_HASH',
	'to_i' : 'TO_I',
	'to_int' : 'TO_INT',
	'to_io' : 'TO_IO',
	'to_path' : 'TO_PATH',
	'to_proc' : 'TO_PROC',
	'to_r' : 'TO_R',
	'to_s' : 'TO_S',
	'to_str' : 'TO_STR',
	'to_sym' : 'TO_SYM',
	'tr' : 'TR',
	'tr!' : 'TR',
	'tr_s' : 'TR_S',
	'tr_s!' : 'TR_S',
	'trace_var' : 'TRACE_VAR',
	'transfer' : 'TRANSFER',
	'transpose' : 'TRANSPOSE',
	'trap' : 'TRAP',
	'truncate' : 'TRUNCATE',
	'trust' : 'TRUST',
	'try_lock' : 'TRY_LOCK',
	'tty?' : 'TTY',
	'tuesday?' : 'TUESDAY',
	'tv_nsec' : 'TV_NSEC',
	'tv_sec' : 'TV_SEC',
	'tv_usec' : 'TV_USEC',
	'uid' : 'UID',
	'unbind' : 'UNBIND',
	'undef_method' : 'UNDEF_METHOD',
	'ungetbyte' : 'UNGETBYTE',
	'ungetc' : 'UNGETC',
	'uniq' : 'UNIQ',
	'uniq!' : 'UNIQ',
	'unlock' : 'UNLOCK',
	'unpack' : 'UNPACK',
	'unshift' : 'UNSHIFT',
	'untaint' : 'UNTAINT',
	'untrace_var' : 'UNTRACE_VAR',
	'untrust' : 'UNTRUST',
	'untrusted?' : 'UNTRUSTED',
	'upcase' : 'UPCASE',
	'upcase!' : 'UPCASE',
	'update' : 'UPDATE',
	'upto' : 'UPTO',
	'puts' : 'PUTS' ,
	'usec' : 'USEC',
	'using' : 'USING',
	'utc' : 'UTC',
	'utc?' : 'UTC',
	'utc_offset' : 'UTC_OFFSET',
	'valid_encoding?' : 'VALID_ENCODING',
	'value' : 'VALUE',
	'value?' : 'VALUE',
	'values' : 'VALUES',
	'values_at' : 'VALUES_AT',
	'wait' : 'WAIT',
	'wakeup' : 'WAKEUP',
	'warn' : 'WARN',
	'wday' : 'WDAY',
	'wednesday?' : 'WEDNESDAY',
	'with_index' : 'WITH_INDEX',
	'with_object' : 'WITH_OBJECT',
	'world_readable?' : 'WORLD_READABLE',
	'world_writable?' : 'WORLD_WRITABLE',
	'writable?' : 'WRITABLE',
	'writable_real?' : 'WRITABLE_REAL',
	'write' : 'WRITE',
	'write_nonblock' : 'WRITE_NONBLOCK',
	'yday' : 'YDAY',
	'year' : 'YEAR',
	'zero?' : 'ZERO',
	'zip' : 'ZIP',
	'zone' : 'ZONE',
	'|' : 'OR',
	'~' : 'TILDA',

}




	





tokens = [
	'NAME','FPNUMBER','NUMBER',
	'PLUS','MINUS','TIMES','DIVIDE','EQUALS', 'illegal','Ands', 'newline',
	'LPAREN','RPAREN','GOOD', 'lbrace', 'rbrace','Seperator','Question' ,'ID','DOT', 'STRING','UMINUS', 'OP_OR','OP_AND' ,'ClassVar', 'keyword', 'Hash', 'equals', 'Identifier', 'COMMENT', 'SemiColon', 'Colon', 'KEYWORD'] 

tokens = tokens + list(reserved.values())


# Tokens

def t_illegal(t) :
	r'[0-9]+[a-zA-Z]+'
	
	return t
## These are the constants needed

def t_FPNUMBER(t):
	r'[+-]?([0-9]+\.[0-9]+|[0-9]+\.[0-9]+)([eE][+-]?[0-9]+)?'
	t.value = float(t.value)
	return t 



def t_NUMBER(t):
	r'\d+'
	t.value = int(t.value)
	return t

def t_OP_AND(t):
    r"&&"
    return t

def t_OP_OR(t):
    r"\|\|"
    return t

t_PLUS    = r'\+'
t_MINUS   = r'-'
t_TIMES   = r'\*'
t_DIVIDE  = r'/'
#t_EQUALS  = r'='
t_LPAREN  = r'\('
t_RPAREN  = r'\)'
t_DOT = r'\.'
t_Seperator = r'\,'
t_SemiColon = r'\;'
t_Colon = r'\:'
t_ClassVar = r'\@'
t_Hash = r'\#'
t_Ands = r'\&'



   



def t_Identifier(t):
	r'[a-zA-Z_][a-zA-Z0-9_]*'   
	for keyword in reserved:

	  if t.value == keyword:
		t.type = reserved.get(t.value)
		return t
	return t
 
def t_EQUALS(t):
	r'[=][=]*'
	for keyword in reserved:

	  if t.value == keyword:
		t.type = reserved.get(t.value)
		return t
	t.type = 'EQUALS'      # Set token type to the expected literal
	return t

def t_keyword(t):
	r'[\+][@]|[-][@]|[\[][\]][\=]*|[\^<>!~|=\[\]\?_a-zA-Z_%\+\*&][<>!~|\[=\]\?_a-zA-Z%\+\*&]*|[a-zA-Z_][a-zA-Z0-9_]*' 
	if t.value == '?':
		t.type= 'Question'
		return t 
	for keyword in reserved:

	  if t.value == keyword:
		t.type = reserved.get(t.value)
		return t
	#t.type = reserved.get(t.value,'ID')
	#return t
 
def t_STRING(t):
  r'(\"(\\.|[^\"\n]|(\\\n))*\") | (\'(\\.|[^\'\n]|(\\\n))*\')'
  t.type = "STRING"
  return t


def t_COMMENT(t):
  r'[ ]*\#[^\n]*'
  t.type = 'COMMENT'
  #return t

#printf("%c", s[4])
#Identifiers code

#def Identifiers    
	

	# t.type = 'NAME'
	# return t
	  # Check for reserved words





literals = [ '{', '}']

def t_lbrace(t):
	r'\{'
	t.type = '{'      # Set token type to the expected literal
	return t

def t_rbrace(t):
	r'\}'
	t.type = '}'      # Set token type to the expected literal
	return t







# Ignored characters
t_ignore = " \t"

# def t_newline(t):
# 	r'\n+'
# 	t.lexer.lineno += t.value.count("\n")
# 	return t

def t_error(t):
	print("Illegal character '%s'" % t.value[0])
	t.lexer.skip(1)

# Build the lexer

lexer = lex.lex()

#inputa = raw_input()
lexer.input(',')


for token in lexer:
        print "Token:", token


