all : binary

binary :
	mkdir -p bin
	cp src/* bin/
	chmod 755 bin/lexer.py
	chmod +x bin/lexer.py
	chmod 755 bin/lexer.py
	chmod +x bin/lexer.py
	chmod 755 bin/lexer.py
	chmod +x bin/lexer.py
	chmod 755 bin/lexer.py
	chmod +x bin/lexer.py


clean :
		rm -r bin
